version : '3'
services:
  loya-mysql:
    container_name: loya-mysql
    image: mysql:5.7
    restart: unless-stopped
    build:
      context: .
      dockerfile: mysql-dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'loya'
      MYSQL_ROOT_PASSWORD: loya@2024
  loya-minio:
    container_name: loya-minio
    restart: unless-stopped
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "loya"
      MINIO_ROOT_PASSWORD: "loya@2024"
    volumes:
      - ./minio/data:/data  # 持久化存储
    command: server /data --console-address ":9001
  loya-redis:
    container_name: loya-redis
    image: redis:7-alpine
    restart: unless-stopped
    build:
      context: .
      dockerfile: redis-dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/home/loya/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/loya/redis/redis.conf
  loya-nginx:
    container_name: loya-nginx
    image: nginx:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx-dockerfile
    ports:
      - "80:80"
    volumes:
      - ./html/dist:/home/loya/projects/loya-ui
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - loya-server
    links:
      - loya-server
      - loya-minio
  loya-server:
    container_name: loya-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: loya-dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./loya/logs:/home/loya/logs
      - ./loya/uploadPath:/home/loya/uploadPath
    depends_on:
      - loya-mysql
      - loya-redis
    links:
      - loya-mysql
      - loya-minio
      - loya-redis