
services:
  common-mysql:
    container_name: common-mysql
    image: mysql:5.7
    restart: unless-stopped
    build:
      context: .
      dockerfile: mysql-dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'common'
      MYSQL_ROOT_PASSWORD: 'app@2024'
  common-minio:
    container_name: common-minio
    restart: unless-stopped
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "app"
      MINIO_ROOT_PASSWORD: "common@2024"
    volumes:
      - ./minio/data:/data  # 持久化存储
    command: server /data --console-address ":9001"
  common-redis:
    container_name: common-redis
    image: redis:7-alpine
    restart: unless-stopped
    build:
      context: .
      dockerfile: redis-dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/home/app/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/app/redis/redis.conf
