
services:
  app-mysql:
    container_name: app-mysql
    image: mysql:5.7
    restart: unless-stopped
    build:
      context: .
      dockerfile: mysql-dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'common'
      MYSQL_ROOT_PASSWORD: 'app@2024'
  app-minio:
    container_name: app-minio
    restart: unless-stopped
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "app"
      MINIO_ROOT_PASSWORD: "common@2024"
    volumes:
      - ./minio/data:/data  # 持久化存储
    command: server /data --console-address ":9001"
  app-redis:
    container_name: app-redis
    image: redis:7-alpine
    restart: unless-stopped
    build:
      context: .
      dockerfile: redis-dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/home/app/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/app/redis/redis.conf
  app-nginx:
    container_name: app-nginx
    image: nginx:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx-dockerfile
    ports:
      - "80:80"
    volumes:
      - ./html/dist:/home/app/projects/app-ui
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app-server
    links:
      - app-server
      - app-minio
  app-server:
    container_name: app-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: app-dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app/logs:/home/app/logs
      - ./app/uploadPath:/home/app/uploadPath
    depends_on:
      - app-mysql
      - app-redis
    links:
      - app-mysql
      - app-minio
      - app-redis