events {}

http {
    charset utf-8;
    # 开启GZIP压缩，提高文件传输效率
    gzip on;                          # 启用GZIP
    gzip_disable "msie6";              # 禁用对老版IE的GZIP支持
    gzip_vary on;                      # 支持响应头Vary
    gzip_proxied any;                  # 启用代理请求的GZIP压缩
    gzip_comp_level 6;                 # 压缩等级，范围1-9，6是一个适中的值
    gzip_buffers 16 8k;                # 分配用于存储GZIP压缩结果的缓冲区
    gzip_http_version 1.1;             # 使用HTTP/1.1协议来压缩
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;  # 压缩的MIME类型

    # 配置缓存，提高静态资源的加载速度
    open_file_cache max=1000 inactive=20s; # 缓存打开的文件，最多缓存1000个，缓存20秒不活跃的文件
    open_file_cache_valid 30s;             # 文件缓存的有效期
    open_file_cache_min_uses 2;            # 最少被使用两次的文件才缓存
    open_file_cache_errors on;             # 缓存文件打开错误信息

    # 限制客户端请求速率，防止过载
    limit_req_zone $binary_remote_addr zone=one:10m rate=1r/s;

    server {
        listen 80;
        server_name localhost;

        # 允许的最大上传文件大小设置为 2GB
        client_max_body_size 2G;

        # 静态文件目录配置
        location / {
            root /home/app/projects/oss;   # 这是容器内的目录
            autoindex on;                  # 启用文件列表展示
            autoindex_exact_size off;      # 文件大小以 KB、MB 单位展示
            autoindex_localtime on;        # 文件时间以本地时间展示
        }

        # 上传文件的配置
        location /uploads {
            root /home/app/projects/oss; # 上传文件存储目录
            client_max_body_size 2G;             # 允许上传最大 2G 文件
            dav_methods PUT DELETE;
            create_full_put_path on;
            dav_access user:rw group:rw all:r;
        }

        # 为静态文件设置缓存时间
        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 30d;                         # 缓存这些类型的文件30天
            add_header Cache-Control "public";    # 启用缓存
        }


    }

    # 超时优化
    send_timeout 30s;              # 发送响应的超时时间
    keepalive_timeout 65s;         # 保持连接的超时时间
    client_body_timeout 12s;       # 客户端发送请求主体的超时时间
    client_header_timeout 12s;     # 客户端发送请求头的超时时间
}
